apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment 
spec:
  selector:
    matchLabels:
      app: hello-app 
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app 
    spec:
      containers:
        - name: hello-app-container
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080

